name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Login no Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Construir e enviar Backend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/order-food-backend:latest ./order-food-backend
          docker push ${{ secrets.DOCKER_USERNAME }}/order-food-backend:latest

      - name: Construir e enviar Frontend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/order-food-frontend:latest ./order-food-front
          docker push ${{ secrets.DOCKER_USERNAME }}/order-food-frontend:latest
